replicaCount: 4

image:
  repository: prayag8tiwari/prayag-new1-pipeline
  tag: "1.0.0-prod"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi

service:
  type: LoadBalancer
  port: 8080

env: "prod"
