apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prayag-new1.fullname" . }}
  labels:
    app: {{ include "prayag-new1.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "prayag-new1.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "prayag-new1.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "prayag-new1.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: {{ .Values.containerPort }}
