replicaCount: 2

image:
  repository: prayag8tiwari/prayag-new1-pipeline
  tag: "1.0.0-prod"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

service:
  type: LoadBalancer
  port: 8080

env: "staging"
