# Development environment values
environment: "dev"

replicaCount: 2

image:
  repository: prayag8tiwari/prayag-new1-pipeline
  tag: "1.0.0-7-dev"
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: "128Mi"
    cpu: "250m"
  requests:
    memory: "64Mi"
    cpu: "100m"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

# Development specific annotations
podAnnotations:
  environment: "dev"
  branch: "dev"