# UAT environment values
environment: "uat"

replicaCount: 3

image:
  repository: prayag8tiwari/prayag-new1-pipeline
  tag: "1.0.0-7-uat"
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: prayag-app-uat.example.com
      paths:
        - path: /
          pathType: Prefix

# UAT specific annotations
podAnnotations:
  environment: "uat"
  branch: "uat"