replicaCount: 4

image:
  repository: prayag8tiwari/prayag-new1-pipeline
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"

podLabels: {}
podAnnotations: {}

containerPort: 8080
